---
  - name: Installing and Launching filebeat
    hosts: webservers
    become: yes
    tasks:

    - name: Download Filebeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install Filebeat .deb file
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Copy the Filebeat Configuration File
      copy: 
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable System Module
      command: filebeat modules enable system

    - name: Setup Filebeat
      command: filebeat setup

    - name: Start Filebeat Service
      command: filebeat -e

    - name: Enable Filebeat on boot
      ansible.builtin.systemd:
        name: filebeat
        enabled: yes